# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/70/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/70/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/camix/Fiuba/Taller/TDP1-Portal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/camix/Fiuba/Taller/TDP1-Portal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/70/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/70/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/camix/Fiuba/Taller/TDP1-Portal/CMakeFiles /home/camix/Fiuba/Taller/TDP1-Portal/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/camix/Fiuba/Taller/TDP1-Portal/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Test

# Build rule for target.
Test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test
.PHONY : Test

# fast build rule for target.
Test/fast:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/build
.PHONY : Test/fast

#=============================================================================
# Target rules for targets named Client

# Build rule for target.
Client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Client
.PHONY : Client

# fast build rule for target.
Client/fast:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/build
.PHONY : Client/fast

#=============================================================================
# Target rules for targets named Editor

# Build rule for target.
Editor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Editor
.PHONY : Editor

# fast build rule for target.
Editor/fast:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/build
.PHONY : Editor/fast

#=============================================================================
# Target rules for targets named Server

# Build rule for target.
Server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Server
.PHONY : Server

# fast build rule for target.
Server/fast:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/build
.PHONY : Server/fast

#=============================================================================
# Target rules for targets named Box2D-cmake

# Build rule for target.
Box2D-cmake: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Box2D-cmake
.PHONY : Box2D-cmake

# fast build rule for target.
Box2D-cmake/fast:
	$(MAKE) -f Box2D/CMakeFiles/Box2D-cmake.dir/build.make Box2D/CMakeFiles/Box2D-cmake.dir/build
.PHONY : Box2D-cmake/fast

client/main.o: client/main.cpp.o

.PHONY : client/main.o

# target to build an object file
client/main.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/client/main.cpp.o
.PHONY : client/main.cpp.o

client/main.i: client/main.cpp.i

.PHONY : client/main.i

# target to preprocess a source file
client/main.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/client/main.cpp.i
.PHONY : client/main.cpp.i

client/main.s: client/main.cpp.s

.PHONY : client/main.s

# target to generate assembly for a file
client/main.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/client/main.cpp.s
.PHONY : client/main.cpp.s

common/AnimatedSprite.o: common/AnimatedSprite.cpp.o

.PHONY : common/AnimatedSprite.o

# target to build an object file
common/AnimatedSprite.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/common/AnimatedSprite.cpp.o
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/common/AnimatedSprite.cpp.o
.PHONY : common/AnimatedSprite.cpp.o

common/AnimatedSprite.i: common/AnimatedSprite.cpp.i

.PHONY : common/AnimatedSprite.i

# target to preprocess a source file
common/AnimatedSprite.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/common/AnimatedSprite.cpp.i
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/common/AnimatedSprite.cpp.i
.PHONY : common/AnimatedSprite.cpp.i

common/AnimatedSprite.s: common/AnimatedSprite.cpp.s

.PHONY : common/AnimatedSprite.s

# target to generate assembly for a file
common/AnimatedSprite.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/common/AnimatedSprite.cpp.s
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/common/AnimatedSprite.cpp.s
.PHONY : common/AnimatedSprite.cpp.s

common/SDLSession.o: common/SDLSession.cpp.o

.PHONY : common/SDLSession.o

# target to build an object file
common/SDLSession.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/common/SDLSession.cpp.o
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/common/SDLSession.cpp.o
.PHONY : common/SDLSession.cpp.o

common/SDLSession.i: common/SDLSession.cpp.i

.PHONY : common/SDLSession.i

# target to preprocess a source file
common/SDLSession.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/common/SDLSession.cpp.i
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/common/SDLSession.cpp.i
.PHONY : common/SDLSession.cpp.i

common/SDLSession.s: common/SDLSession.cpp.s

.PHONY : common/SDLSession.s

# target to generate assembly for a file
common/SDLSession.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/common/SDLSession.cpp.s
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/common/SDLSession.cpp.s
.PHONY : common/SDLSession.cpp.s

common/Sprite.o: common/Sprite.cpp.o

.PHONY : common/Sprite.o

# target to build an object file
common/Sprite.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/common/Sprite.cpp.o
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/common/Sprite.cpp.o
.PHONY : common/Sprite.cpp.o

common/Sprite.i: common/Sprite.cpp.i

.PHONY : common/Sprite.i

# target to preprocess a source file
common/Sprite.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/common/Sprite.cpp.i
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/common/Sprite.cpp.i
.PHONY : common/Sprite.cpp.i

common/Sprite.s: common/Sprite.cpp.s

.PHONY : common/Sprite.s

# target to generate assembly for a file
common/Sprite.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/common/Sprite.cpp.s
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/common/Sprite.cpp.s
.PHONY : common/Sprite.cpp.s

common/StageView.o: common/StageView.cpp.o

.PHONY : common/StageView.o

# target to build an object file
common/StageView.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/common/StageView.cpp.o
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/common/StageView.cpp.o
.PHONY : common/StageView.cpp.o

common/StageView.i: common/StageView.cpp.i

.PHONY : common/StageView.i

# target to preprocess a source file
common/StageView.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/common/StageView.cpp.i
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/common/StageView.cpp.i
.PHONY : common/StageView.cpp.i

common/StageView.s: common/StageView.cpp.s

.PHONY : common/StageView.s

# target to generate assembly for a file
common/StageView.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/common/StageView.cpp.s
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/common/StageView.cpp.s
.PHONY : common/StageView.cpp.s

common/Window.o: common/Window.cpp.o

.PHONY : common/Window.o

# target to build an object file
common/Window.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/common/Window.cpp.o
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/common/Window.cpp.o
.PHONY : common/Window.cpp.o

common/Window.i: common/Window.cpp.i

.PHONY : common/Window.i

# target to preprocess a source file
common/Window.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/common/Window.cpp.i
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/common/Window.cpp.i
.PHONY : common/Window.cpp.i

common/Window.s: common/Window.cpp.s

.PHONY : common/Window.s

# target to generate assembly for a file
common/Window.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/common/Window.cpp.s
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/common/Window.cpp.s
.PHONY : common/Window.cpp.s

editor/BrickBlockImage.o: editor/BrickBlockImage.cpp.o

.PHONY : editor/BrickBlockImage.o

# target to build an object file
editor/BrickBlockImage.cpp.o:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/BrickBlockImage.cpp.o
.PHONY : editor/BrickBlockImage.cpp.o

editor/BrickBlockImage.i: editor/BrickBlockImage.cpp.i

.PHONY : editor/BrickBlockImage.i

# target to preprocess a source file
editor/BrickBlockImage.cpp.i:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/BrickBlockImage.cpp.i
.PHONY : editor/BrickBlockImage.cpp.i

editor/BrickBlockImage.s: editor/BrickBlockImage.cpp.s

.PHONY : editor/BrickBlockImage.s

# target to generate assembly for a file
editor/BrickBlockImage.cpp.s:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/BrickBlockImage.cpp.s
.PHONY : editor/BrickBlockImage.cpp.s

editor/BrickBlockImageContainer.o: editor/BrickBlockImageContainer.cpp.o

.PHONY : editor/BrickBlockImageContainer.o

# target to build an object file
editor/BrickBlockImageContainer.cpp.o:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/BrickBlockImageContainer.cpp.o
.PHONY : editor/BrickBlockImageContainer.cpp.o

editor/BrickBlockImageContainer.i: editor/BrickBlockImageContainer.cpp.i

.PHONY : editor/BrickBlockImageContainer.i

# target to preprocess a source file
editor/BrickBlockImageContainer.cpp.i:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/BrickBlockImageContainer.cpp.i
.PHONY : editor/BrickBlockImageContainer.cpp.i

editor/BrickBlockImageContainer.s: editor/BrickBlockImageContainer.cpp.s

.PHONY : editor/BrickBlockImageContainer.s

# target to generate assembly for a file
editor/BrickBlockImageContainer.cpp.s:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/BrickBlockImageContainer.cpp.s
.PHONY : editor/BrickBlockImageContainer.cpp.s

editor/Editor.o: editor/Editor.cpp.o

.PHONY : editor/Editor.o

# target to build an object file
editor/Editor.cpp.o:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/Editor.cpp.o
.PHONY : editor/Editor.cpp.o

editor/Editor.i: editor/Editor.cpp.i

.PHONY : editor/Editor.i

# target to preprocess a source file
editor/Editor.cpp.i:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/Editor.cpp.i
.PHONY : editor/Editor.cpp.i

editor/Editor.s: editor/Editor.cpp.s

.PHONY : editor/Editor.s

# target to generate assembly for a file
editor/Editor.cpp.s:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/Editor.cpp.s
.PHONY : editor/Editor.cpp.s

editor/Menu.o: editor/Menu.cpp.o

.PHONY : editor/Menu.o

# target to build an object file
editor/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/Menu.cpp.o
.PHONY : editor/Menu.cpp.o

editor/Menu.i: editor/Menu.cpp.i

.PHONY : editor/Menu.i

# target to preprocess a source file
editor/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/Menu.cpp.i
.PHONY : editor/Menu.cpp.i

editor/Menu.s: editor/Menu.cpp.s

.PHONY : editor/Menu.s

# target to generate assembly for a file
editor/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/Menu.cpp.s
.PHONY : editor/Menu.cpp.s

editor/MetalBlockImage.o: editor/MetalBlockImage.cpp.o

.PHONY : editor/MetalBlockImage.o

# target to build an object file
editor/MetalBlockImage.cpp.o:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/MetalBlockImage.cpp.o
.PHONY : editor/MetalBlockImage.cpp.o

editor/MetalBlockImage.i: editor/MetalBlockImage.cpp.i

.PHONY : editor/MetalBlockImage.i

# target to preprocess a source file
editor/MetalBlockImage.cpp.i:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/MetalBlockImage.cpp.i
.PHONY : editor/MetalBlockImage.cpp.i

editor/MetalBlockImage.s: editor/MetalBlockImage.cpp.s

.PHONY : editor/MetalBlockImage.s

# target to generate assembly for a file
editor/MetalBlockImage.cpp.s:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/MetalBlockImage.cpp.s
.PHONY : editor/MetalBlockImage.cpp.s

editor/Stage.o: editor/Stage.cpp.o

.PHONY : editor/Stage.o

# target to build an object file
editor/Stage.cpp.o:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/Stage.cpp.o
.PHONY : editor/Stage.cpp.o

editor/Stage.i: editor/Stage.cpp.i

.PHONY : editor/Stage.i

# target to preprocess a source file
editor/Stage.cpp.i:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/Stage.cpp.i
.PHONY : editor/Stage.cpp.i

editor/Stage.s: editor/Stage.cpp.s

.PHONY : editor/Stage.s

# target to generate assembly for a file
editor/Stage.cpp.s:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/Stage.cpp.s
.PHONY : editor/Stage.cpp.s

editor/main.o: editor/main.cpp.o

.PHONY : editor/main.o

# target to build an object file
editor/main.cpp.o:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/main.cpp.o
.PHONY : editor/main.cpp.o

editor/main.i: editor/main.cpp.i

.PHONY : editor/main.i

# target to preprocess a source file
editor/main.cpp.i:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/main.cpp.i
.PHONY : editor/main.cpp.i

editor/main.s: editor/main.cpp.s

.PHONY : editor/main.s

# target to generate assembly for a file
editor/main.cpp.s:
	$(MAKE) -f CMakeFiles/Editor.dir/build.make CMakeFiles/Editor.dir/editor/main.cpp.s
.PHONY : editor/main.cpp.s

server/BrickBlock.o: server/BrickBlock.cpp.o

.PHONY : server/BrickBlock.o

# target to build an object file
server/BrickBlock.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/server/BrickBlock.cpp.o
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/BrickBlock.cpp.o
.PHONY : server/BrickBlock.cpp.o

server/BrickBlock.i: server/BrickBlock.cpp.i

.PHONY : server/BrickBlock.i

# target to preprocess a source file
server/BrickBlock.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/server/BrickBlock.cpp.i
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/BrickBlock.cpp.i
.PHONY : server/BrickBlock.cpp.i

server/BrickBlock.s: server/BrickBlock.cpp.s

.PHONY : server/BrickBlock.s

# target to generate assembly for a file
server/BrickBlock.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/server/BrickBlock.cpp.s
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/BrickBlock.cpp.s
.PHONY : server/BrickBlock.cpp.s

server/Coordinate.o: server/Coordinate.cpp.o

.PHONY : server/Coordinate.o

# target to build an object file
server/Coordinate.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/server/Coordinate.cpp.o
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/Coordinate.cpp.o
.PHONY : server/Coordinate.cpp.o

server/Coordinate.i: server/Coordinate.cpp.i

.PHONY : server/Coordinate.i

# target to preprocess a source file
server/Coordinate.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/server/Coordinate.cpp.i
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/Coordinate.cpp.i
.PHONY : server/Coordinate.cpp.i

server/Coordinate.s: server/Coordinate.cpp.s

.PHONY : server/Coordinate.s

# target to generate assembly for a file
server/Coordinate.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/server/Coordinate.cpp.s
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/Coordinate.cpp.s
.PHONY : server/Coordinate.cpp.s

server/DiagonalMetalBlock.o: server/DiagonalMetalBlock.cpp.o

.PHONY : server/DiagonalMetalBlock.o

# target to build an object file
server/DiagonalMetalBlock.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/server/DiagonalMetalBlock.cpp.o
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/DiagonalMetalBlock.cpp.o
.PHONY : server/DiagonalMetalBlock.cpp.o

server/DiagonalMetalBlock.i: server/DiagonalMetalBlock.cpp.i

.PHONY : server/DiagonalMetalBlock.i

# target to preprocess a source file
server/DiagonalMetalBlock.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/server/DiagonalMetalBlock.cpp.i
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/DiagonalMetalBlock.cpp.i
.PHONY : server/DiagonalMetalBlock.cpp.i

server/DiagonalMetalBlock.s: server/DiagonalMetalBlock.cpp.s

.PHONY : server/DiagonalMetalBlock.s

# target to generate assembly for a file
server/DiagonalMetalBlock.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/server/DiagonalMetalBlock.cpp.s
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/DiagonalMetalBlock.cpp.s
.PHONY : server/DiagonalMetalBlock.cpp.s

server/MetalBlock.o: server/MetalBlock.cpp.o

.PHONY : server/MetalBlock.o

# target to build an object file
server/MetalBlock.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/server/MetalBlock.cpp.o
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/MetalBlock.cpp.o
.PHONY : server/MetalBlock.cpp.o

server/MetalBlock.i: server/MetalBlock.cpp.i

.PHONY : server/MetalBlock.i

# target to preprocess a source file
server/MetalBlock.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/server/MetalBlock.cpp.i
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/MetalBlock.cpp.i
.PHONY : server/MetalBlock.cpp.i

server/MetalBlock.s: server/MetalBlock.cpp.s

.PHONY : server/MetalBlock.s

# target to generate assembly for a file
server/MetalBlock.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/server/MetalBlock.cpp.s
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/MetalBlock.cpp.s
.PHONY : server/MetalBlock.cpp.s

server/Stage.o: server/Stage.cpp.o

.PHONY : server/Stage.o

# target to build an object file
server/Stage.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/server/Stage.cpp.o
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/Stage.cpp.o
.PHONY : server/Stage.cpp.o

server/Stage.i: server/Stage.cpp.i

.PHONY : server/Stage.i

# target to preprocess a source file
server/Stage.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/server/Stage.cpp.i
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/Stage.cpp.i
.PHONY : server/Stage.cpp.i

server/Stage.s: server/Stage.cpp.s

.PHONY : server/Stage.s

# target to generate assembly for a file
server/Stage.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/server/Stage.cpp.s
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/Stage.cpp.s
.PHONY : server/Stage.cpp.s

server/main.o: server/main.cpp.o

.PHONY : server/main.o

# target to build an object file
server/main.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/main.cpp.o
.PHONY : server/main.cpp.o

server/main.i: server/main.cpp.i

.PHONY : server/main.i

# target to preprocess a source file
server/main.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/main.cpp.i
.PHONY : server/main.cpp.i

server/main.s: server/main.cpp.s

.PHONY : server/main.s

# target to generate assembly for a file
server/main.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/main.cpp.s
.PHONY : server/main.cpp.s

tests/tests.o: tests/tests.cpp.o

.PHONY : tests/tests.o

# target to build an object file
tests/tests.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/tests/tests.cpp.o
.PHONY : tests/tests.cpp.o

tests/tests.i: tests/tests.cpp.i

.PHONY : tests/tests.i

# target to preprocess a source file
tests/tests.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/tests/tests.cpp.i
.PHONY : tests/tests.cpp.i

tests/tests.s: tests/tests.cpp.s

.PHONY : tests/tests.s

# target to generate assembly for a file
tests/tests.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/tests/tests.cpp.s
.PHONY : tests/tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Test"
	@echo "... Client"
	@echo "... edit_cache"
	@echo "... Editor"
	@echo "... Server"
	@echo "... Box2D-cmake"
	@echo "... client/main.o"
	@echo "... client/main.i"
	@echo "... client/main.s"
	@echo "... common/AnimatedSprite.o"
	@echo "... common/AnimatedSprite.i"
	@echo "... common/AnimatedSprite.s"
	@echo "... common/SDLSession.o"
	@echo "... common/SDLSession.i"
	@echo "... common/SDLSession.s"
	@echo "... common/Sprite.o"
	@echo "... common/Sprite.i"
	@echo "... common/Sprite.s"
	@echo "... common/StageView.o"
	@echo "... common/StageView.i"
	@echo "... common/StageView.s"
	@echo "... common/Window.o"
	@echo "... common/Window.i"
	@echo "... common/Window.s"
	@echo "... editor/BrickBlockImage.o"
	@echo "... editor/BrickBlockImage.i"
	@echo "... editor/BrickBlockImage.s"
	@echo "... editor/BrickBlockImageContainer.o"
	@echo "... editor/BrickBlockImageContainer.i"
	@echo "... editor/BrickBlockImageContainer.s"
	@echo "... editor/Editor.o"
	@echo "... editor/Editor.i"
	@echo "... editor/Editor.s"
	@echo "... editor/Menu.o"
	@echo "... editor/Menu.i"
	@echo "... editor/Menu.s"
	@echo "... editor/MetalBlockImage.o"
	@echo "... editor/MetalBlockImage.i"
	@echo "... editor/MetalBlockImage.s"
	@echo "... editor/Stage.o"
	@echo "... editor/Stage.i"
	@echo "... editor/Stage.s"
	@echo "... editor/main.o"
	@echo "... editor/main.i"
	@echo "... editor/main.s"
	@echo "... server/BrickBlock.o"
	@echo "... server/BrickBlock.i"
	@echo "... server/BrickBlock.s"
	@echo "... server/Coordinate.o"
	@echo "... server/Coordinate.i"
	@echo "... server/Coordinate.s"
	@echo "... server/DiagonalMetalBlock.o"
	@echo "... server/DiagonalMetalBlock.i"
	@echo "... server/DiagonalMetalBlock.s"
	@echo "... server/MetalBlock.o"
	@echo "... server/MetalBlock.i"
	@echo "... server/MetalBlock.s"
	@echo "... server/Stage.o"
	@echo "... server/Stage.i"
	@echo "... server/Stage.s"
	@echo "... server/main.o"
	@echo "... server/main.i"
	@echo "... server/main.s"
	@echo "... tests/tests.o"
	@echo "... tests/tests.i"
	@echo "... tests/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

